### PR TITLE
Fixed undefined variables when upgrading to Ansible 2.2.0. and the el…

### PR DESCRIPTION
**Pull request by mickael-ange**
…asticsearch role is skipped using a when condition at the playbook level.

### CODE REVIEW

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by jakommo** [comment]
thanks @mickael-ange, did you sign the CLA?

**Comment by jakommo** [comment]
@dliappis looks like the "Jenkins, test it!" trigger does not work anymore, can you check please?

**Comment by elasticdog** [comment]
Looking at the logs on build-eu-00, it's complaining that the hook for this particular repository doesn't have a secret associated with it:

```
INFO: Checking issue comment '@dliappis looks like the "Jenkins, test it!" trigger does not work anymore, can you check please? ' for repo elastic/ansible-elasticsearch
Nov 30, 2016 6:01:01 PM org.jenkinsci.plugins.ghprb.GhprbGitHubAuth checkSignature
SEVERE: Request doesn't contain a signature. Check that github has a secret that should be attached to the hook
```

...I don't know if someone else changed things recently to require that, or if they added a secret to the global config (which makes it now fail for the repos that don't have it configured). Give me a bit and I'll see if I can track it down.

**Comment by mickael-ange** [comment]
@jakommo Yes, I did sign after I saw the CLA check failed.

**Comment by jakommo** [comment]
@mickael-ange cool, I can see it now.
@elasticdog Thanks for looking into this. I wasn't involved in the setup but maybe @gingerwizard knows?

**Comment by dliappis** [comment]
jenkins, test it

**Comment by dliappis** [comment]
jenkins, test it

**Comment by dliappis** [comment]
jenkins, test it

**Comment by dliappis** [comment]
jenkins, test it

**Comment by dliappis** [comment]
@elasticdog @jakommo Testing via jenkins is now ok

**Comment by jakommo** [comment]
@dliappis awesome, thanks for fixing it.

**Comment by jakommo** [comment]
Merged, thanks for the PR @mickael-ange

**Pull request merged**
