### PR TITLE
naming unnamed tasks

### PR DESCRIPTION
**Pull request by cl0udf0x**
I've added names to all tasks in relation to issue: 

#402 "Give a name to anonymous set_fact tasks".

### CODE REVIEW

**Comment by cl0udf0x** [comment]
I've just signed the CLA.

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins this this please

**Comment by Crazybus** [comment]
jenkins restest this please

**Pull request merged**
