### PR TITLE
alwasy gather the es_major_version variables

### PR DESCRIPTION
**Pull request by titan-architrave**

### CODE REVIEW

**Comment by pemontto** [comment]
Need this, I can no longer run with `-t config` 😢

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @titan-architrave ,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement

**Comment by titan-architrave** [comment]
On 4. Sep 2019, at 10:36, Julien Mailleret <notifications@github.com> wrote:

Hi @titan-architrave <https://github.com/titan-architrave> ,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement <https://www.elastic.co/contributor-agreement>

**Comment by titan-architrave** [comment]
[Please_DocuSign_Elastic_Contributor_Agreemen.pdf](https://github.com/elastic/ansible-elasticsearch/files/3573607/Please_DocuSign_Elastic_Contributor_Agreemen.pdf)

**Comment by jmlrt** [comment]
I removed your CLA file as we don't need to post it on GitHub, our CLA bot detect it automatically:

Screenshot 2019-09-04 at 11 16 13

**Pull request merged**
