### PR TITLE
Fix - restart check

### PR DESCRIPTION
**Pull request by johnr-spindance**

### CODE REVIEW

**Comment by johnr-spindance** [comment]
Referencing https://github.com/elastic/ansible-elasticsearch/issues/270

**Comment by marcjay** [comment]
I've run into this issue as well @johnr-spindance  - please can this be merged?

**Comment by johnr-spindance** [comment]
@marcjay, I'm glad I'm not the only one. Unfortunately I am not able to merge this change. I need one of the maintainers of this repo to review and approve in order to push forward.

**Comment by johnr-spindance** [comment]
@bbaassssiiee, I understand where you are coming from. Because I am in need of a quick fix and I am not the original author, I maintained the approach previously used. If a more elegant method is desired, I'd prefer the maintainers of this repo make those changes - or someone could create a new branch and make the desired changes that produce the desired results and closing out this pull.

Because this hasn't been merged, I'm using my forked branch in order to be able to deploy properly in our environment.

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by marcjay** [comment]
What's the next step for getting this merged?

**Comment by gingerwizard** [comment]
Testing this now as i work through the backlog.

**Comment by gingerwizard** [comment]
LGTM

**Comment by marcjay** [comment]
Great, thanks for merging!

**Comment by johnr-spindance** [comment]
Woohoo!

**Comment by johnr-spindance** [comment]
Thanks for merging!

**Pull request merged**
