### PR TITLE
bump versions for kitchen-ci

### PR DESCRIPTION
**Pull request by philippkahr**
Hi,

I run the entire kitchen suite locally and no errors/issues where detected.

I need to bump the version for kitchen-test, kitchen-docker so that SLES and OpenSuse is proper supported.

### CODE REVIEW

**Comment by philippkahr** [comment]
I guess all the failures in the CI can be related to the "internet is down" currently. I will retrigger the build when "internet is alive" again.

**Comment by philippkahr** [comment]
!test

**Comment by philippkahr** [comment]
jenkins test this please

**Comment by philippkahr** [comment]
I guess this is nothing that I can fix. Could somebody change the Jenkins job details? https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+pull-request/configure as I only have read access. Maybe we can change the CI to parse the needed version from the `.ruby-version` ? 

```
export RBENV_VERSION='2.5.7'
```

```
13:50:21 ++ command rbenv rehash
13:50:21 + rbenv local 2.5.7
13:50:21 + local command
```

```
13:50:22 bundle install
13:50:22 + bundle install
13:50:29 Fetching gem metadata from https://rubygems.org/.........
13:50:29 chef-utils-17.1.35 requires ruby version >= 2.6, which is incompatible with the
13:50:29 current version, ruby 2.5.7p206
```

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request closed without merging**
