### PR TITLE
Support for Activating License

### PR DESCRIPTION
**Pull request by gingerwizard**
This merges @barryib efforts on license activation.  However, in testing i was forced to make several changes:

1. We mount the license.json into the kitchen file into the docker container on run - at /tmp/license.json. Users wishing to run xpack tests will need to set the env variable ES_XPACK_LICENSE_FILE to run the xpack tests to a local license file.  This will be set on the test servers.  The test then loads the contents from the /tmp/license.json in the container. This is required as ansible actually runs locally on the container with kitchen.
2. Moved the activation to a handler - tests were failing as ES wasn't started after x-pack install so the license couldn't be loaded.
3. Fixed some syntax errors on the check for shield installed.
4. Minor refactoring so the start check is in elasticseach-shield.yml
5. I adjusted to work with 2.x. We can merge into the 5.x branch separately.
6. ES_XPACK_LICENSE_UID is tricky as serverspec is run on the docker container - so its not available and will probably change from host to host. We just check the license is valid - again adjusted for 2.x

@barryib please review. @elasticdog or @dliappis need to discuss deploying this with yourselves as well to ensure we are comfortable there will be no leakage of the license file on the test infra - which will likely have a significant time expiry

### CODE REVIEW

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
Seems like we were suffering from https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/983302

I suspect many users will encounter this so we refresh the java certs in the java install as well.

**Comment by gingerwizard** [comment]
single failure on ubuntu 16.04, looks like an infra issue

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
Merging @barryib all good

**Comment by barryib** [comment]
Thank you @gingerwizard <https://github.com/gingerwizard> for this great
work. I'm currently in holidays (about 3 months) without pc and a limit
access to my workspace. This is why I couldn't answer or review it before.

---
Thierno IB. BARRY / IT Ninja

[image: Twitter]  <https://twitter.com/barryib>[image: LinkedIn]
<https://fr.linkedin.com/in/barryib>[image: Github]
<https://github.com/barryib>

2017-01-05 21:20 GMT+06:30 Dale McDiarmid <notifications@github.com>:

**Pull request merged**
