### PR TITLE
Update elasticsearch-xpack.yml

### PR DESCRIPTION
**Pull request by nicladas**
Original fact setting fails on update plays for Debian with : redhat_elasticsearch_install_from_repo is undefined.

Updated the conditional to allow multiple plays.

### CODE REVIEW

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by nicladas** [comment]
I'm not sure that failure is related to my update. I can try and deploy again on my system. It is using ubuntu 16.04 and worked fine.

**Comment by Crazybus** [comment]
@nicladas Not you :) Thanks a lot for the contribution!

I'm slowly replacing these flaky tests with something that is actually checking the results. This test which is failing is checking an md5 hash which is not the best idea ever. 

Ideally all of these `curl | md5` tests should be updated to look more something like: https://github.com/elastic/ansible-elasticsearch/blob/3bdcd8fe4d0afdc2da5e12475b2093bb2bb3326b/test/integration/helpers/serverspec/xpack_spec.rb#L182-L189

```
08:21:59        Failures:
08:21:59        
08:21:59          1) Xpack Tests Command "curl -s localhost:9200/_xpack/security/user -u es_admin:changeMeAgain | md5sum | grep b6a1293c343e745a508c74778c9be8bb" exit_status should eq 0
08:21:59             Failure/Error: its(:exit_status) { should eq 0 }
08:21:59               
08:21:59               expected: 0
08:21:59                    got: 1
08:21:59               
08:21:59               (compared using ==)
08:21:59               /bin/sh -c curl\ -s\ localhost:9200/_xpack/security/user\ -u\ es_admin:changeMeAgain\ \|\ md5sum\ \|\ grep\ b6a1293c343e745a508c74778c9be8bb
```

**Comment by nicladas** [comment]
Cool, thanks @Crazybus, glad I could help a little :)

**Pull request merged**
