### PR TITLE
Fixes bug #326 and adds the option to configure mail

### LINKED ISSUE #326: es_version_lock: fires hold es version before actual installation
If I set  es_version_lock, the outcome is the version is hold before actual installation, and useless.

```
TASK [elasticsearch : Debian - Add elasticsearch repository] ***********************************************************************************************
ok: [138.x.xx.xx] => (item={u'repo': u'deb http://packages.elastic.co/elasticsearch/5.x/debian stable main', u'state': u'absent'})
changed: [138.x.xx.xx] => (item={u'repo': u'deb https://artifacts.elastic.co/packages/5.x/apt stable main', u'state': u'present'})

TASK [elasticsearch : Debian - hold elasticsearch version] *************************************************************************************************
changed: [138.x.xx.xx]

TASK [elasticsearch : Debian - Ensure elasticsearch is installed] ******************************************************************************************
changed: [138.x.xx.xx]

```

### PR DESCRIPTION
**Pull request by gekkeharry13**
Fixes #326 
Added code to allow the configuration of x-pack notifications through mail.
Apparently a syntax error in parenthesis is also fixed, but can't remember I did that.

### CODE REVIEW

**Comment by itsmed** [comment]
jenkins please test this

**Comment by itsmed** [comment]
jenkins test this please

**Comment by itsmed** [comment]
Thanks for this PR @gekkeharry13. The build is currently failing with
```17:00:56        TASK [elasticsearch : Copy Configuration File] *********************************
17:00:56        fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'path_repo' is undefined"}```
which is a variable you've added. You'll need to add a default value in [defaults/main.yml](https://github.com/elastic/ansible-elasticsearch/blob/master/defaults/main.yml) so this works for those who aren't using a custom setting.

The `es_mail_config` option is awesome! Could you update the [README](https://github.com/elastic/ansible-elasticsearch/blob/master/README.md) so that people know it exists and how to use it?

**Comment by gekkeharry13** [comment]
Good points! Added the documentation and made path_repo an if statement so it is optional (as it is not always used)
Also added an if statement to authentication settings in the E-mail config.

**Comment by itsmed** [comment]
@gekkeharry13 sorry, I can't read, or type :)

> path_repo an if statement so it is optional

You addressed the concern I meant to bring up, so jenkins magic time. 

jenkins test this

**Comment by itsmed** [comment]
Hey @gekkeharry13 we're still seeing [build failures](https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+pull-request/47/OS=ubuntu-1604,TEST_TYPE=standard,VERSION=6.x,label=swarm/console) with 

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'es_path_repo' is undefined"}`

**Comment by gekkeharry13** [comment]
hmm sorry about that. Still getting used to ansible and jinja. Had to use "{% if es_path_repo is defined %}" instead of {% if es_path_repo %}. I have now verified it on my local machine, there it worked without the variable available. So hopefully jenkins likes the new master....

**Comment by itsmed** [comment]
no worries, my apologies. I got distracted and didn't finish the suggestion. Great to hear you have it working locally, let's run the build!

jenkins test this

**Comment by itsmed** [comment]
@gekkeharry13 this is looking close. We'll need to set a default value for `action_auto_create_index`

From the most recent build: 

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'action_auto_create_index' is undefined"}`

**Comment by gekkeharry13** [comment]
Hi itsmed, I have adjusted the name to match the standard (es_action_auto_create_index). As far as I can see here "https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html". The default value should be true, so added that to the defaults/main.yml

**Comment by gekkeharry13** [comment]
@itsmed Was testing a bit with all settings and came across the fact that it es_action_auto_create_index should also be able to be set as an array with allowed indices, so adjusted the code accordingly. It was a bit of a hassle working it out, but it should work properly now!

**Comment by gekkeharry13** [comment]
hmm woopsie... My git skills are lacking pretty bad... Just pushed a set of commits to master while I was just trying to sync my local repo with the current master. I will try to figure out how to reverse things

**Comment by gekkeharry13** [comment]
hmm maybe you can also review the code and provide feedback on if you like it to be pushed to your repo? I can imagine that SSL configuration might be a valuable addition, but for now it might be a bit too specific to my environment. If you can help me fix that I can make it available to you guys

**Comment by itsmed** [comment]
Let's see what the tests say first, then regarding the `SSL` configuration we'll review :)
jenkins test this

**Comment by itsmed** [comment]
I think for simplicity's sake @gekkeharry13 you should `git revert` to [this commit](cc28b6149af9866455f9b1b90ac601596e4635a4) and add the change you described in [this comment](https://github.com/elastic/ansible-elasticsearch/pull/445#issuecomment-386315724) so we can get this PR set, and open a second PR with the `SSL` changes you propose. The second round of changes are causing the build to fail at this time. What do you think?

**Comment by gekkeharry13** [comment]
Okee, I think we are back were we were... My history is a mess now, but ah well. PS is there a way to get in touch privately. I also am building Logstash and Kibana templates, which I am willing to share

**Comment by itsmed** [comment]
> PS is there a way to get in touch privately. I also am building Logstash and Kibana templates, which I am willing to share

If you can send a link I'd be happy to help evaluate the kibana/logstash playbooks. In general we prefer to keep communication public to allow others to participate in the conversation, and it encourages accountability.

**Comment by itsmed** [comment]
jenkins test this

**Comment by gekkeharry13** [comment]
Kibana is located here: https://github.com/gekkeharry13/ansible-kibana. Logstash will be uploaded shortly after. They are currently a bit focused on my personal build, but when that part is over I will make them as generic as possible

**Comment by itsmed** [comment]
It looks like `is defined` got removed from the `es_path_repo` if statement during the revert @gekkeharry13 .
You had it set properly [in this commit](https://github.com/elastic/ansible-elasticsearch/pull/445/commits/7640a0383a99f698ef1c9949f22cdeb5b51579bc), could you add that back in? I think the other if/elif/else you have around `action.auto_correct_index` looks correct still.

**Comment by gekkeharry13** [comment]
it is back now, missed that part I guess

**Comment by itsmed** [comment]
jenkins test this

**Comment by itsmed** [comment]
Sorry for the delay here @gekkeharry13. A change was made that may help ensure that the tests aren't transient failures, so I'm going to use the "update branch" button and re-run the tests to see if that helps. The last check had failed with `fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'action_auto_create_index' is undefined"}` again.

**Comment by gekkeharry13** [comment]
Awh man, I am sorry I messed up my repo this bad.... I managed to work in a seperate branch with my new changes now, so it no longer interferes. I have added es_action_auto_create_index: true back to my defaults/main.yml. I checked the repo and there are only references to "es_action_auto_create_index" not to "action_auto_create_index"

**Comment by itsmed** [comment]
jenkins test this

**Comment by itsmed** [comment]
I think we're super close now @gekkeharry13 This time the [build failed](https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+pull-request/13/OS=ubuntu-1604,TEST_TYPE=standard,VERSION=6.x,label=swarm/console) because `es_mail_config` is undefined. Looks like you're checking for `account` in the dict here:
` {% if es_mail_config['account'] is defined %} `

`22:32:37        fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'es_mail_config' is undefined"}`

**Comment by gekkeharry13** [comment]
I have updated the es_mail_config statement again :)

**Comment by itsmed** [comment]
jenkins test this

**Comment by gekkeharry13** [comment]
So everything is fine now? I am currently actively developing the following Ansible repo's:
- https://github.com/gekkeharry13/ansible-kibana
- https://github.com/gekkeharry13/ansible-logstash
- https://github.com/gekkeharry13/ansible-beats-linux

They are currently working for (as I do not have much customisation to paths and such), if you like we can discuss if there is a way to provide them in a decent fashion to Elastic in order for other customers to use.

**Comment by itsmed** [comment]
Yes the PR has been merged. We do have plans to provide playbooks for our other products, so thanks for offering these up @gekkeharry13! We'll take a look at your playbooks here and assess how to move forward.

**Comment by gekkeharry13** [comment]
Okay great! Let me know if you need something from me!

**Pull request merged**
