### PR TITLE
Added additional Ansible tags for XPACK tasks

### PR DESCRIPTION
**Pull request by strootman**

### CODE REVIEW

**Comment by gingerwizard** [comment]
@strootman any chance you could repush with changes given all of the recent updates?

**Comment by strootman** [comment]
@gingerwizard Done.

**Comment by gingerwizard** [comment]
apologies @strootman mind resolving the conflicts again and ill merge. I want to do a 5.6.1 tag and push to galaxy asap. I'd like to include this PR.

**Comment by strootman** [comment]
@gingerwizard I won't be able to get to this today.

**Pull request closed without merging**
