### PR TITLE
Add es_keystore variable

### LINKED ISSUE #684: Keystore Configuration
**Add suppot for elasticsearch.keystore entries**:
Some Elasticsearch features like watcher outputs or AD integration need entries stored in the elasticsearch keystore. As far as I can see this is currently not supported. Although the settings can be done outside of the playbook with a separate task it would still be easier to have this supported by the playbook.

**Elasticsearch version** 7.6.1

### PR DESCRIPTION
**Pull request by Bernhard-Fluehmann**
Added variable to support adding and removing of elasticsearch.keystore entries

Fix #684

### CODE REVIEW

**Comment by jmlrt** [comment]
still valid

**Comment by issamzinati** [comment]
Any chance that this pr would be accepted?

**Comment by jmlrt** [comment]
Hi @issamzinati @Bernhard-Fluehmann, sorry, we don't have the workload currently to review this PR.

**Comment by Bernhard-Fluehmann** [comment]
@bndabbs Please hold on with this pull request. I have created a new implementation with a simpler ansible variable structure
I will create a new pull request with the new implementation until the end of the week

**Comment by Bernhard-Fluehmann** [comment]
@bndabbs This pull request is obsoleted by #757
Please have a look and let me know what you think about it.

**Comment by jmlrt** [comment]
Closing this one as #757 replace it.

**Pull request closed without merging**
