### PR TITLE
use become: yes when root is needed

### PR DESCRIPTION
**Pull request by brad**
Hi folks,
We prefer not to give roles carte blanche access, and feel it is good practice for tasks to request root when needed, so I went through and added `become: yes` to all the tasks that require root access.
Thanks!

### CODE REVIEW

**Comment by brad** [comment]
I've signed the CLA, what do I need to do to fix the failing check? :point_up:

**Comment by juanpaulo** [comment]
when can this be merged?

**Comment by regit** [comment]
I don't see this merged ?

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by gingerwizard** [comment]
Will merge for 5.5.2.

**Comment by gingerwizard** [comment]
There are alot of conflicts but ill try and merge this tomorrow.

**Comment by brad** [comment]
@gingerwizard Resolved!

**Comment by gingerwizard** [comment]
@brad we will merge https://github.com/elastic/ansible-elasticsearch/pull/379 this and then this. Just waiting for a review on the above.

**Comment by gingerwizard** [comment]
@brad mind making the changes for conflicts and we'll run the tests.

**Comment by brad** [comment]
@gingerwizard Sure, done!

**Comment by gingerwizard** [comment]
LGTM

**Pull request merged**
