### PR TITLE
Correct Error detection for plugin install and check logging.yml is removed

### PR DESCRIPTION
**Pull request by gingerwizard**

### CODE REVIEW

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by dliappis** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by dliappis** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
I made some changes. Will push later when I'm home

**Comment by gingerwizard** [comment]
jenkins, test it

**Pull request merged**
