### PR TITLE
Template out the base of repo URLs

### PR DESCRIPTION
**Pull request by branen**
Some popular artifact caches (e.g. Artifactory) do not provide `HTTP CONNECT` endpoints and thus aren't supported by `es_proxy_host` and `es_proxy_port`.  This patch templates out the scheme and authority components (i.e. "https://artifacts.elastic.co" ) of the apt and yum repo URLs to accommodate the use of such artifact caches.

### CODE REVIEW

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
@branen Thanks for adding this in! CI is green but the [CLA checker](http://www.elasticsearch.org/contributor-agreement/) is still complaining.

**Comment by branen** [comment]
Hi, @Crazybus!  I wrote this at work, and while we have a great workflow for [DCO-style license grants](https://developercertificate.org/), we don't have a standardized workflow for CLA-style grants, which makes them take a little longer.  If y'all can accept this on a DCO, I'm happy to sign off on one; in the meantime, I'm working on getting the corporate CLA approved.

**Comment by branen** [comment]
Hi, @Crazybus!  I wrote this at work, and while we have a great workflow for [DCO-style license grants](https://developercertificate.org/), we don't have a standardized workflow for CLA-style grants, which makes them take a little longer.  If y'all can accept this on a DCO, I'm happy to sign off on one; in the meantime, I'm working on getting the corporate CLA approved.

**Comment by Crazybus** [comment]
> If y'all can accept this on a DCO, I'm happy to sign off on one; in the meantime, I'm working on getting the corporate CLA approved.

I'm afraid not :( The status check literally prevents me from merging this in until it passes. 

image

**Comment by branen** [comment]
@Crazybus, I signed the individual-from-a-company CLA earlier today, and AFAIK, my employer signed the corporate CLA a few days ago.  Is there more than a few hours' lag between Adobe Sign and Github, or should I assume that something went wrong?

**Comment by Crazybus** [comment]
Hey @branen!

Can you check that you have the email address you used for [this commit](https://github.com/elastic/ansible-elasticsearch/pull/529.patch) in your settings at https://github.com/settings/emails  and also that this is the same email you used to sign with? I'm not 100% sure that the email in the commit needs to match, but the one you signed with needs to at least be in your email settings.

**Comment by branen** [comment]
Ah, nice catch!  I did sign the CLA with the same address I used in the commit, but I hadn't added that address to my GitHub account.  That's done now, and I'll check back this evening to see if the CLA checker has picked it up.

**Comment by branen** [comment]
Hey @Crazybus!  I've made sure that the email address from my CLA and the commit is in my profile, and I've also made sure that my employer's signed the corporate CLA with my GitHub username, but the CLA checker's still unsatisfied.  Any ideas?  Once this patch lands, I've got another one to submit, and I'd love to get the process rolling.

Thanks!

**Comment by Crazybus** [comment]
Hey @branen,

We recently found an issue with our CLA checker and new signatures were not flowing in. Could you try resigning it once more? It should work this time 🤞

**Comment by branen** [comment]
Hey, @Crazybus, the CLA checker is finally green (hooray!), but now devops-ci seems to be the issue.  I've been checking back periodically over the last four days and it hasn't seemed to budge.  Any ideas?

**Comment by Crazybus** [comment]
> Hey, @Crazybus, the CLA checker is finally green (hooray!), but now devops-ci seems to be the issue. I've been checking back periodically over the last four days and it hasn't seemed to budge. Any ideas?

I'll give it a poke.

jenkins test this please

**Comment by Crazybus** [comment]
The build passed (https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+pull-request/129/) but you hit the "update branch" button which adds a new commit. The status for devops-ci then goes to pending until I authorise another test. 

Thanks again for your work here! Sorry that it took so long to get things actually merged in. 

> Once this patch lands, I've got another one to submit, and I'd love to get the process rolling.

If you are still up for this I promise things will be much smoother/quicker next time :)

**Pull request merged**
