### PR TITLE
Removed array_to_string in 2 places

### PR DESCRIPTION
**Pull request by smalenfant**
Configuration files were not created properly. Not sure how that could have worked in the past, interested to know what I could be doing wrong.

### CODE REVIEW

**Comment by smalenfant** [comment]
Fixes #104

**Comment by gingerwizard** [comment]
As expected this has failed tests.  Are you using Ansible 2.0 as required?
This assumes the array is passed and not a string.  Prior to 2.0 it would be passed as a string.

**Comment by smalenfant** [comment]
I believe this works with both now. But let me double check as I am using
the vagrant ansible provisioner. I'll also check the failed tests.

**Comment by gingerwizard** [comment]
@smalenfant I satisfied this works with 2.0 or do you want to modify the pull request?

**Comment by smalenfant** [comment]
Maybe the problem is related on how the hosts are specified. Here's how I used it..

`discovery.zen.ping.unicast.hosts: "host1:9300, host2:9300, host3:9300"`

Normally I think this should be a list.

**Comment by gingerwizard** [comment]
@smalenfant path.data is handled differently from discovery.zen.ping.unicast.hosts.  The former you can declare as a list or string.  The latter is passed within the config map so will just be serialised as either a string or array - depending on how you pass it.  Either should work.

The array_to_str only works on 2.0 ansible.  Removing causes all tests to fail so i can't accept this pull request. Please open another issue if you are able to reproduce.

**Pull request closed without merging**
