### PR TITLE
Add custom parameters for controlling number and size of main cluster…

### PR DESCRIPTION
**Pull request by dcleric**
… logfiles handled by Log4j2
Define size and count of ES main log-files for better control to avoid filesystem overflow.

### CODE REVIEW

**Comment by dekhtyarev** [comment]
@gingerwizard @jakommo 
Can you see this PR?

**Comment by barryib** [comment]
@dekhtyarev I think it's similar to https://github.com/elastic/ansible-elasticsearch/pull/347.

**Comment by dekhtyarev** [comment]
@barryib, in general, yes.
We will be happy with any of the options :)

**Comment by barryib** [comment]
ping @gingerwizard. What do you think?

**Comment by gingerwizard** [comment]
@dekhtyarev @barryib i think #347 is actually more flexible and powerful. Assuming no objections i'll merge that one.

**Pull request closed without merging**
