### PR TITLE
Using tests as filters is deprecated

### PR DESCRIPTION
**Pull request by victorgs**
Instead of using
`result|version_compare` use `result is version_compare`.

### CODE REVIEW

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by victorgs** [comment]
It's failing in ubuntu 14.04 but it seems not related with this.

FYI `W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch`

**Comment by verboEse** [comment]
I just signed the CLA, so this check should be ok now :)

**Comment by victorgs** [comment]
I just signed it right now ^^)

but thanks a lot : )

**Pull request merged**
