### PR TITLE
Allow for cluster-common config

### PR DESCRIPTION
**Pull request by ashokc**
Here is the driver for this change request

Most use cases for this role are in setting up a single cluster in a single run of the playbook. There are ES configurations that are shared across all host-groups & nodes in a cluster. For example the 'discovery hosts' can be the same across all nodes - master or data. In most use cases there is a single ES instance per host, so 9200 & 9300 are given and available. The config/scripts folder is kept in sync across the cluster nodes. So perhaps we can keep the playbook short & simple by separating out common ES configs from those that actually have to be different across host groups...    

We can allow the user to provide these common parameters under "group_vars/all.json" for example. In my case it looks like:

more group_vars/all.json

`{
  "private_iface" : "eth0",
  "public_iface" : "eth1",
  "masterHosts" : "{% for host in groups['es-master-nodes'] %} {{ hostvars[host]['ansible_'+public_iface]['ipv4']['address'] }}:9300 {% endfor %}"
,
  "es_scripts" : "false",
  "es_templates" : "false",
  "es_version_lock" : "false",
  "es_plugins" : [ {"plugin" : "ingest-geoip"} ],
  "common_es_config" : {"cluster.name": "es-cluster", "discovery.zen.ping.unicast.hosts" : "{{ masterHosts.split() }}", "http.port": 9200, "transp
ort.tcp.port": 9300, "bootstrap.memory_lock": false}
}`

In my case I have chosen to compute 'discovery hosts' from the known masterNodes group...

For example my inventory.yml looks like: (other users can use similar approaches that work for their inventory json/ini files)

es-master-nodes:
  hosts:

    es-master-1:
      ansible_host: 192.168.33.25
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/es-master-1/virtualbox/private_key

es-data-nodes:
  hosts:

    es-data-1:
      ansible_host: 192.168.33.26
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/es-data-1/virtualbox/private_key

    es-data-2:
      ansible_host: 192.168.33.27
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/es-data-2/virtualbox/private_key

### CODE REVIEW

**Comment by ashokc** [comment]
Just signed the CLA

**Comment by ashokc** [comment]
Are the checks still failing? Thx.

**Comment by karmi** [comment]
Hi @ashokc, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/ansible-elasticsearch/pull/399.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by ashokc** [comment]
I see, I did not realize - thanks for the tip - Karmi. Added the other e-mail as well to the github profile now.

**Comment by Crazybus** [comment]
@ashokc Thanks for this! Could you please add a small note to the README.md to explain that the option exists and how to use it? Ideally also a small test added to the `config` suite too to prove that it works.

Could you also please rebase your branch against master?

Thanks! Michael

**Comment by ashokc** [comment]
Michael,

I rebased my fork on the latest, & added a snippet of detail to README.md as how it can be used to simplify the configuration. I am not sure how to write formal "tests" but I have tested it on  with Vagrant on my laptop, and on aws ec2 instances - all Ubuntu 16.04. Hopefully that is sufficient, as this change is mostly for simplification purposes and to keep the playbook readable. Thank you. Ashok

**Comment by Crazybus** [comment]
Thanks Ashok! The docs update is perfect!

Re: testing. Next thing on my to do list is to document how to properly use the local test-kitchen environment that jenkins is running so make it easier for people to write and run the tests.

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
test this please

**Comment by barryib** [comment]
Hi @Crazybus and @ashokc,

I'm coming late probably, but what prevent you doing this by playing with ansible variable precedency? Because `es_config` is a dict variable which can be overwritten or merged by ansible when loading varibles. Doing this for a while now.

## Method 1
#### In `group_vars/all`
```yml
es_config:
  cluster.name: "es-cluster",
  discovery.zen.ping.unicast.hosts: "elastic02:9300",
  bootstrap.memory_lock: false

# You can add all common vars here
```
#### In `group_vars/data_node`

```yml
es_config:
  node.data: true,
  node.master: false,
  http.port: 9200,
  transport.tcp.port: 9300

# You can add all specifics vars here
```
#### In Ansible
To let ansible merge dict for you, change the `hash_behaviour` setting in your `ansible.cfg`. 
More info in [doc](http://docs.ansible.com/ansible/latest/intro_configuration.html#hash-behaviour)
```ini
hash_behaviour = merge
```
## Method 2

```yml
es_config: "{{ common_es_config | combine(custom_es_config, recursive=True) }}"
```

**Comment by Crazybus** [comment]
@barryib This is a really good suggestion and sounds like it would fit perfectly. @ashokc Would the pattern suggested above work for your use case?

**Comment by ashokc** [comment]
@barrib and @crazybus I should try out Method 2 that Barry indicates. Looking for a least intrusive change to the code base, while letting users supply the cluster common config in just one place. If you have already tested it Barry, I am fine with it. Thank you

**Comment by Crazybus** [comment]
@ashokc I'm going to close this for now. Please feel free to reopen it though if that method that @barryib suggested doesn't work!

**Pull request closed without merging**
