### PR TITLE
Removed bare variables

### PR DESCRIPTION
**Pull request by qk4l**
Issue #86

### CODE REVIEW

**Comment by qk4l** [comment]
Hi, I've signed CLA. How to run checks?

**Comment by jakommo** [comment]
jenkins, test it

**Comment by qk4l** [comment]
I added two additional commits to PR.

62c16c6:  `with_fileglob` loop read only files, so we must specify destination directory to make it works.
c7e449f: To allow users add ansible-elasticsearch repo as submodule to their Ansible project we should add *.pyc files that created every time in `filter_plugins/` directory

**Comment by jakommo** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
Unfortunately we have build issues that I'll try to resolve later today

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
This is currently failing @qk4l on two of the ubuntu tests.  I'll re-run shortly to see if we can reproduce as the errors alude to a temporary network blip.

**Comment by qk4l** [comment]
@gingerwizard I saw that previously time it failed on the same task `Ensure Java is installed` but on Centos builder.

**Comment by gingerwizard** [comment]
I believe this was test infra issues so...

jenkins, test it

**Comment by jakommo** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
Ok tests are now passing as we've made some improvements to the infrastructure. @jakommo Please hold off testing pull requests as we're trying to improve stability.

LGTM.

**Pull request merged**
