### PR TITLE
Add binary prefix for version 5.x

### PR DESCRIPTION
**Pull request by veger**
As requested in #182 a PR for the 5.x branch.

Copied from #178:

The `plugin` executable for Elasticsearch version 5.0.0, is renamed `elasticsearch-plugin`.

This PR uses the new executable name when `es_version` indicates that version 5 (or higher) is used.

Some other minor plugin-related changes:

* Removed `sed -n '1!p' | cut -d '-' -f2-` as the executable just returns a list of installed plugins (or is this also new in version 5.x?)
* Added task name for 'installed plugins check'
* Result of 'remove plugins' task is stored in `plugin_removed`

Note that I have updated the xpack/* files as well, but this is untested. Since it also contains some shell filters (`tail -n +2`), I would assume it does not work with version 5 as well...

### CODE REVIEW

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by veger** [comment]
Fixed situation where `es_plugins` is undefined, resulting in `es_binary_prefix` being undefiend as well. Now `es_binary_prefix` defined no matter what.

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by veger** [comment]
While setting up the (failing) test, the _rspec-retry_ ruby gem was not found, is it possible that this influences the CentOS 7 standard-1x test? (as this is now the only test that fails)

**Comment by jakommo** [comment]
Looks like the real problem was that the node did not start:

```
Node listening
listening in port 9200 (FAILED - 1)

version check
should be reported as version 1.7.3 (FAILED - 2)
```

Not sure if this is caused by the rspec-retry ruby gem.
let's run the test again .

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by veger** [comment]
Looks like it was an hiccup in the test scripts

**Comment by jakommo** [comment]
Merged, thanks again @veger

**Pull request merged**
