### PR TITLE
Change basestring by str to make it python3 compatible

### PR DESCRIPTION
**Pull request by viscat**
- Change basestring by str to make it python3 compatible

### CODE REVIEW

**Comment by gingerwizard** [comment]
@viscat can you please sign the CLA?

**Comment by viscat** [comment]
Done

**Comment by gingerwizard** [comment]
@viscat this causes the tests to fail. Initial investigation appears to indicate this is the result of they way ansible is passing the value. the type check of str on python 2.7, which is what the tests use seems to fail when "/var/lib/elasticsearch" is passed - this results in the values being treated as a set of chars by the loop `return [str(value+suffix) for value in values]`

Hence path.data becomes

`path.data: //localhost-node1,v/localhost-node1,a/localhost-node1,r/localhost-node1,//localhost-node1,l/localhost-node1,i/localhost-node1,b/localhost-node1,//localhost-node1,e/localhost-node1,l/localhost-node1,a/localhost-node1,s/localhost-node1,t/localhost-node1,i/localhost-node1,c/localhost-node1,s/localhost-node1,e/localhost-node1,a/localhost-node1,r/localhost-node1,c/localhost-node1,h/localhost-node1`

**Comment by gingerwizard** [comment]
@viscat im testing but i think

```
from six import string_types
if isinstance(values, string_types):
```

is robust and will work across python 2 and 3.

**Comment by gingerwizard** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/364
Introduces the above.

**Comment by gingerwizard** [comment]
Thanks @viscat i believe we have a solution through #364. Thankyou for addressing this.

**Comment by viscat** [comment]
Oh, sorry and thank you very much @gingerwizard

**Pull request merged**
