### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by gingerwizard**
Includes:

Gem lock file
Default to dliappis images

### CODE REVIEW

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by dliappis** [comment]
jenkins, test it

**Comment by dliappis** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Pull request merged**
