### PR TITLE
require admin role to use update-alternatives

### PR DESCRIPTION
**Pull request by chaintng**
promote `update-alternatives` command to run as admin role

I have problem when i tried to run this ansible script to Google Compute Engine
It show below error
```
TASK [elasticsearch : correct java version selected] *****************************************************************************
fatal: [35.186.157.183]: FAILED! => {"changed": false, "failed": true, "msg": "Specified path  does not exist"}
        to retry, use: --limit @/.../Projects/ansible-elasticsearch/site.retry
```

After debug, it's because `java_full_path` has empty value because `update-alternatives` got error but hidden by `failed_when: False`

It look like, `update-alternatives` need to run by admin role

### CODE REVIEW

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
The single test failure is from a flaky test.

image

@chaintng Thanks for the fix here!

**Comment by chaintng** [comment]
Woohooo, my PR got merged. Thank you!

**Comment by Crazybus** [comment]
@chaintng yay! I also created a PR to fix the flaky test: https://github.com/elastic/ansible-elasticsearch/pull/450

**Pull request merged**
