### PR TITLE
Upgraded to 5.3.1

### PR DESCRIPTION
**Pull request by igayoso**
Upgraded elastic search to last version (5.3.1)

### CODE REVIEW

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by jlandersen** [comment]
Any update on this? our patching is a bit on hold :-)

**Comment by igayoso** [comment]
@jlandersen I'm going to upgrade to last ES version because this is old right now but I remember the problems with this PR was Jenkins problems with the tests so I'm not sure if it will be merge soon...

**Comment by jlandersen** [comment]
Alright thanks @igayoso - so 5.4.1 incoming? :-)

**Comment by jlandersen** [comment]
Hi - Any update on this (or latest ES)? Our patching/upgrading has gone a bit stale because of this

**Comment by gingerwizard** [comment]
@jlandersen im going to move to 5.5.1, run the test and make sure they pass. If so, ill make a PR and this will be closed.

**Comment by gingerwizard** [comment]
Closing in favour of https://github.com/elastic/ansible-elasticsearch/pull/358

**Pull request closed without merging**
