### PR TITLE
stop using deprecated version_compare

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @lebauce, 
Thanks for this PR, `version_compare` has been replaced by `version` in [ansible 2.5](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#version-comparison).
As this role is currently requiring Ansible [2.4.2 as minimal version](https://github.com/elastic/ansible-elasticsearch/blob/master/meta/main.yml#L10), we would need to upgrade minimal version if merging this. I just need to do a few more test with Ansible 2.42, to decide if that's something we can do.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by cafferata** [comment]
Hi @jmlrt, have you succeeded in testing the minimum Ansible version(s)? I also ran into it and implemented the same (local) fix to get it working. It would be nice to get this back in master. Is there something that I can help with?

**Comment by jmlrt** [comment]
Jenkins test this please

**Comment by cafferata** [comment]
When can we expect a release/tag?

**Comment by jmlrt** [comment]
Releases are only created when we have a new release for the full Elastic Stack.
Hopefully, this should happen pretty soon.

**Comment by cafferata** [comment]
Thanks for this explanation.

**Comment by jmlrt** [comment]
FYI, 7.7.0 was just released: https://github.com/elastic/ansible-elasticsearch/releases/tag/7.7.0

**Pull request merged**
