### PR TITLE
adding es 6.x support

### PR DESCRIPTION
**Pull request by toddlers**
Adding support for ES 6.x

Tested on Ubuntu
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

### CODE REVIEW

**Comment by karmi** [comment]
Hi @toddlers, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/ansible-elasticsearch/pull/405.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by toddlers** [comment]
@karmi  updated my email address in my profile

**Comment by chemeugene** [comment]
Are you tried to install x-pack in 6.0.0 ? 
It seems there are troubles similar to https://github.com/elastic/puppet-elasticsearch/issues/877

**Comment by karmi** [comment]
Thanks, @toddlers, the CLA check is now green.

**Comment by pmachaj** [comment]
Is there a plan to merge this PR anytime soon? I would like to use the role with ES 6.x.
Thanks for the fix.

**Comment by Crazybus** [comment]
Hi @toddlers!

 For the last few months this playbook hasn't had an active maintainer. I'm now stepping up to take ownership of this playbook with the immediate goal of getting 6.x support tested and working. 

Unfortunately there were already three open pull requests with varying levels of 6.x support. This meant I had the hard job of picking the pull request which appeared to be the most complete and start fixing up the tests to run on 5.x and 6.x. This PR ended up being https://github.com/elastic/ansible-elasticsearch/pull/408 because it also contained documentation updates. I have just opened PR: https://github.com/elastic/ansible-elasticsearch/pull/412 where I am fixing up all the tests to make sure they are passing for 5.x and 6.x across all platforms. 

I have also added some pull request [automated testing](https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+pull-request/) to make it easier to contribute in the future. 

So thank you so much for your contribution and I hope to see more contributions again from you in the future.

Cheers,

Michael

**Comment by Crazybus** [comment]
@pmachaj 6.x support is almost ready to be merged #412 is where you can keep an eye on it. I'll make sure to ping you again when it is released.

**Comment by Crazybus** [comment]
@pmachaj [6.1.3](https://github.com/elastic/ansible-elasticsearch/releases/tag/6.1.3) has been released!

**Comment by pmachaj** [comment]
Thank you!

**Pull request closed without merging**
