### PR TITLE
Support elasticsearch-keystore entries

### PR DESCRIPTION
**Pull request by Bernhard-Fluehmann**
@jmlrt Here you go

### CODE REVIEW

**Comment by Bernhard-Fluehmann** [comment]
@jmlrt Can you please check what's still wrong with the Contribution license?

**Comment by jmlrt** [comment]
@Bernhard-Fluehmann, it seems that you have some issue with your git configuration and GitHub doesn't recognize these commits as coming from your GH user:

Screenshot 2021-02-02 at 14 54 09

(GH see 2 authors and don't match them with your profile picture).

Also I found the CLA you signed but I think you did a typo in your email. 

Could you fix your GH config and the commits and eventually re-sign CLA to fix the typo in your email?

**Comment by Bernhard-Fluehmann** [comment]
@jmlrt Email was missing in GH profile. At least commit user looks better now. Working on the CA

**Comment by Bernhard-Fluehmann** [comment]
@jmlrt Can you tell me please what's the typo in sla, since it used to work

**Comment by jmlrt** [comment]
> @jmlrt Can you tell me please what's the typo in sla, since it used to work

I think your email adress in CLA contains `struff` while that should be `stuff`.

**Comment by Bernhard-Fluehmann** [comment]
@jmlrt New CLA submitted. Please confirm

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
@Bernhard-Fluehmann, this is still failling and your commits are still not recognized by GitHub as coming from you:

Screenshot 2021-02-03 at 11 46 17

**Comment by Bernhard-Fluehmann** [comment]
@jmlrt Ok, now I am getting puzzled. I have set the username and mail correctly in my git client and I don't know what do do else.
I am using Bernhard-Fluehmann (my GitHub user.name) and bernhard.fluehmann@realstuff.ch (My Git user.mail). What's still wrong with it?

**Comment by Bernhard-Fluehmann** [comment]
@jmlrt The only thing is that I am commiting to our fork of the repo (RealStuff/ansible-elasticsearch) and create the pull-request from there. It's not a private repo but instead a repo of our company account

**Comment by Bernhard-Fluehmann** [comment]
@jmlrt BTW, this is the output of my console
Bildschirmfoto 2021-02-03 um 12 07 11

**Comment by jmlrt** [comment]
Using GitHub API, here is what I see for one of your previous commit which was recognized by GitHub:

https://github.com/elastic/ansible-elasticsearch/pull/757/commits/aa95b67941cc6694d67eaec317683e42db0af944

```console
➜  ~ curl -H "Accept: application/vnd.github.v3+json" \
 https://api.github.com/repos/elastic/ansible-elasticsearch/commits/aa95b67941cc6694d67eaec317683e42db0af944|jq '.commit'
{
  "author": {
    "name": "bernhard.fluehmann",
    "email": "bernhard.fluehmann@realstuff.ch",
    "date": "2021-01-20T18:42:39Z"
  },
  "committer": {
    "name": "bernhard.fluehmann",
    "email": "bernhard.fluehmann@realstuff.ch",
    "date": "2021-01-20T18:52:50Z"
  },
  "message": "Added keystore entry support",
  "tree": {
    "sha": "34a84102475215b117ab7b9b43edebe5c8db94a7",
    "url": "https://api.github.com/repos/elastic/ansible-elasticsearch/git/trees/34a84102475215b117ab7b9b43edebe5c8db94a7"
  },
  "url": "https://api.github.com/repos/elastic/ansible-elasticsearch/git/commits/aa95b67941cc6694d67eaec317683e42db0af944",
  "comment_count": 0,
  "verification": {
    "verified": false,
    "reason": "unsigned",
    "signature": null,
    "payload": null
  }
}
```

Here is what I get for one of your new commits which are not recognized:

https://github.com/elastic/ansible-elasticsearch/pull/767/commits/e66f4665ccac1a4d78922473e0fca4239fc90a0e

```console
➜  ~ curl -H "Accept: application/vnd.github.v3+json" \
 https://api.github.com/repos/elastic/ansible-elasticsearch/commits/e66f4665ccac1a4d78922473e0fca4239fc90a0e|jq .commit
{
  "author": {
    "name": "Bernhard-Fluehmann",
    "email": "Bernhard.Fluehmann@<ANOTHER_EMAIL>.com",
    "date": "2021-02-02T13:00:59Z"
  },
  "committer": {
    "name": "Bernhard-Fluehmann",
    "email": "Bernhard.Fluehmann@<ANOTHER_EMAIL>.com",
    "date": "2021-02-02T13:00:59Z"
  },
  "message": "Support elasticsearch-keystore entries",
  "tree": {
    "sha": "20e7dda3560dc0a03621c86c0dd7d431606e32e9",
    "url": "https://api.github.com/repos/elastic/ansible-elasticsearch/git/trees/20e7dda3560dc0a03621c86c0dd7d431606e32e9"
  },
  "url": "https://api.github.com/repos/elastic/ansible-elasticsearch/git/commits/e66f4665ccac1a4d78922473e0fca4239fc90a0e",
  "comment_count": 0,
  "verification": {
    "verified": false,
    "reason": "unsigned",
    "signature": null,
    "payload": null
  }
}
```

**Comment by Bernhard-Fluehmann** [comment]
@jmlrt Now?

**Pull request closed without merging**
