### PR TITLE
Fix idempotency for both supported CentOS versions

### PR DESCRIPTION
**Pull request by fourstepper**
Fixes https://github.com/elastic/ansible-elasticsearch/issues/746

### CODE REVIEW

**Comment by bndabbs** [comment]
Thanks for taking the time to dig into this @fourstepper! I'm creating a CentOS 8 machine to test against, as I wasn't able to replicate the issue using CentOS 7.

**Comment by fourstepper** [comment]
@bndabbs On CentOS 7, the formatting of yum versionlock list is different than on CentOS 8 - I have tested this side by side on the two machines and the method proposed worked well for me on both sides.

Let me know if there is anything that needs editing or anything at all :)

**Comment by fourstepper** [comment]
Btw, I noticed that you have some CI in place which is not molecule. Have you given molecule a look? I think it's awesome for testing roles and/or entire playbooks (and ansible content in general)

https://github.com/ansible-community/molecule

**Review by bndabbs — APPROVED** [review]
Validated against CentOS 7 and 8 👍

**Comment by bndabbs** [comment]
> Btw, I noticed that you have some CI in place which is not molecule. Have you given molecule a look? I think it's awesome for testing roles and/or entire playbooks (and ansible content in general)
> 
> https://github.com/ansible-community/molecule

I wasn't involved in setting up this CI, so I can't speak to why Molecule wasn't chosen. It's possible @jmlrt may have some better insight there. I am familiar with Molecule though, and agree that it is an awesome tool!

**Comment by bndabbs** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
> > Btw, I noticed that you have some CI in place which is not molecule. Have you given molecule a look? I think it's awesome for testing roles and/or entire playbooks (and ansible content in general)
> > [ansible-community/molecule](https://github.com/ansible-community/molecule)
> 
> I wasn't involved in setting up this CI, so I can't speak to why Molecule wasn't chosen. It's possible @jmlrt may have some better insight there. I am familiar with Molecule though, and agree that it is an awesome tool!

Yep, tbh I prefer Molecule too. I wasn't there yet but AFAIK, when this role and the related tests were created in 2015, Molecule didn't exist yet and so [Test Kitchen](https://kitchen.ci/) was implemented. Now, despite Molecule being more adapted for Ansible tests, migrating to it is simply not a priority.

**Pull request merged**
