### PR TITLE
Changes to log4j2.properties introduced in ES 5.2.0

### PR DESCRIPTION
**Pull request by strootman**
After installing version `5.2.0` on Ubuntu 16.04 via _apt_, I noticed some small changes to the default `log4j2.properties`.

### CODE REVIEW

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by strootman** [comment]
I just rebased this. 
The previous build failed on the apt step, which has nothing to do with the changes.

       TASK [elasticsearch : Debian - Ensure elasticsearch is installed] **************
       fatal: [localhost]: FAILED! => {"cache_update_time": 1486031235, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'elasticsearch=5.1.2'' failed: E: Version '5.1.2' for 'elasticsearch' was not found\n", "stderr": "E: Version '5.1.2' for 'elasticsearch' was not found\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}

**Comment by strootman** [comment]
Jenkins, test it!

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
ok fixed license issues.
jenkins, test it

**Comment by gingerwizard** [comment]
LGTM. Merging.

**Pull request merged**
