### PR TITLE
For  #36 - Add support for creating optional elasticsearch user and group

### PR DESCRIPTION
**Pull request by jerrac**
Here's the pull request. :) Per https://github.com/elastic/ansible-elasticsearch/issues/36#issuecomment-198418652

### CODE REVIEW

**Comment by gingerwizard** [comment]
@jerrac apologies some other build issues associated with https://github.com/neillturner/kitchen-ansible/issues/7 resolving. Will test this once we resolve.

**Comment by gingerwizard** [comment]
@jerrac Can we simplify this to just be es_user_uid & es_group_id? If either are specified we apply them to the elasticsearch user?

Also i think its worth raising an issue to be able to specify the user name i.e. change it from elasticsearch.  I suggest we assume this user exists - relying on other roles/playbook to create it.

**Comment by jerrac** [comment]
@gingerwizard I'll switch to es_user_id and es_group_id.

> If either are specified we apply them to the elasticsearch user?

So, get ride of ```es_optional_user: True|False```, and just use ```es_user_id is defined or es_group_id is defined``` on the appropriate tasks?

> Also i think its worth raising an issue to be able to specify the user name i.e. change it from elasticsearch. I suggest we assume this user exists - relying on other roles/playbook to create it.

Don't we already have that? ```es_user```, and ```es_group``` in defaults/main.yml.

**Comment by gingerwizard** [comment]
@jerrac yes we do! thanks :) I was confused because your pull uses literal "elasticsearch" rather than es_user and es_group.

Agreed re the other changes

**Comment by gingerwizard** [comment]
@jerrac LGTM.  I'll test it shortly.

I think its worth adding a quick server spec test. Maybe to the config-2x and config-1x suites.  Are you happy to do this or shall i add?

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by jerrac** [comment]
I haven't used kitchen yet. I remember hearing about it once and thinking I should learn it. Heh. 

So, would adding tests for this just involve adding the vars to one of the playbooks in the test/integration directory?

**Comment by gingerwizard** [comment]
@jerrac The tests seemed to have failed. It appears you need explicit is defined checks. It also worth checking the parameters are defined and not empty.

Yes ideally a test would use the parameters in one of the test playbooks - probably [config](https://github.com/elastic/ansible-elasticsearch/blob/master/test/integration/config.yml) is best.  Server spec can then be used confirm the user id and group id were set correctly after the role had been applied [here](https://github.com/elastic/ansible-elasticsearch/blob/master/test/integration/helpers/serverspec/config_spec.rb).

**Comment by jerrac** [comment]
I don't need to edit the config_spec.rb files, right?

**Comment by gingerwizard** [comment]
Yes you can add it there. It will then run for be tested for 1x and 2x. 
http://serverspec.org/resource_types.html#user
Is probably what you want.

**Comment by jerrac** [comment]
Would this work for config-2x/serverspec/default_spec.rb? (Since those are the values I set in the config.yml file.)

```ruby
require 'config_spec'
require 'user_spec'
require 'group_spec'

describe 'Config Tests v 2.x' do
  include_examples 'config::init', "2.1.0"
end

describe group('elasticuser') do
  it { should exist }
end

describe group('elasticuser') do
  it { should have_gid 333 }
end

describe user('elasticuser') do
  it { should exist }
end

describe user('elasticuser') do
  it { should belong_to_group 'elasticuser' }
end

describe user('elasticuser') do
  it { should have_uid 333 }
end
```

btw, thanks for coaching me through this stuff. :smile:

**Comment by jerrac** [comment]
Or maybe I should stick those in [config_spec.rb](https://github.com/elastic/ansible-elasticsearch/blob/master/test/integration/helpers/serverspec/config_spec.rb).

Speaking of that file, would this [section](https://github.com/elastic/ansible-elasticsearch/blob/master/test/integration/helpers/serverspec/config_spec.rb#L38) cause the tests to fail if the user is not _elasticsearch_? 

If so, should I keep the ```es_user```, and ```es_group``` values as "elasticsearch" in the test?

**Comment by gingerwizard** [comment]
Hi
Put it in config_sepc and then it will run for 1.x and 2.x.  You can drop the 2.x test then.  I would keep the username as elasticsearch - we currently dont have code to create an alternative user just set the uid and guid.

**Comment by gingerwizard** [comment]
Hey @jerrac thanks for this. We will test this, we're just experiencing some issues with the build env not clearing up docker images properly.  Once we've resolved this ill run it and hopefully merged. Please feel free to contribute elsewhere, its really appreciated.

**Comment by gingerwizard** [comment]
infra problems hopefully solved so without further ado... 

jenkins, test it

**Comment by gingerwizard** [comment]
@jerrac in an effort to improve stability the role has changed which is now causing conflicts. Can you please resolve and repush?

**Comment by jerrac** [comment]
@gingerwizard Erm, did those changes help? Or am I missing something?

**Comment by dliappis** [comment]
jenkins, test it

**Comment by dliappis** [comment]
jenkins, test it

**Comment by jerrac** [comment]
I rebased to master. Did that help? 

And after poking around Jenkins some more, I found where to view the errors that caused the failure. Which is what I was missing when I was checking things earlier. :\

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
@jerrac all tests pass! merging. Thanks for the contribution!

**Pull request merged**
