### PR TITLE
Fixes AttributeError

### PR DESCRIPTION
**Pull request by kenorb**
This fixes the following error:

```
TASK [Set fact users_roles]

The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 144, in run
    res = self._execute()
  File "/usr/local/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 576, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/local/lib/python3.7/site-packages/ansible/playbook/task.py", line 268, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/local/lib/python3.7/site-packages/ansible/playbook/base.py", line 382, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/local/lib/python3.7/site-packages/ansible/template/__init__.py", line 584, in template
    disable_lookups=disable_lookups,
  File "/usr/local/lib/python3.7/site-packages/ansible/template/__init__.py", line 539, in template
    disable_lookups=disable_lookups,
  File "/usr/local/lib/python3.7/site-packages/ansible/template/__init__.py", line 804, in do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "filter_plugins/custom.py", line 27, in extract_role_users
    for user,details in users.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

fatal: [foo.cloudapp.azure.com]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

When using Ansible 2.8.0 with Python 3.7.4. As per this [post](https://stackoverflow.com/a/30418498/55075), `iteritems()` has been removed from Python 3. It seems other parts of code is using `items()` instead.

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @kenorb,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by kenorb** [comment]
> Hi @kenorb,
> Thanks for your PR.
> Can you sign the CLA: https://www.elastic.co/contributor-agreement

I don't want to sign anything. If that's the problem, create your own PR, use my code freely.

**Comment by jmlrt** [comment]
@kenorb,
Thanks for your work!
Signing CLA is mandatory for PR merge, so I'll close this one and I created #619 to adress it.

**Pull request closed without merging**
