### PR TITLE
Fixing boolean expressions syntax when installing templates/license

### PR DESCRIPTION
**Pull request by konasp**

### CODE REVIEW

**Comment by konasp** [comment]
Sorry, forgot about - CLA. Just signed it.

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by strootman** [comment]
@jakommo Not counting the `x-pack` failures, this particular run seems to have been a transient test harness failure? 

    Error response from daemon: Container be63aa96add5ef55c8389b12c8de584b796b9d0e8304610cc0828b373afb7bb4 is not running

#### RE: `x-pack` failure trend
The last 2 automated tests of `x-pack` seem to have failed for the following reason across all distributions;

    RUNNING HANDLER [elasticsearch : Activate ES license (with security authentication)] ***
       fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

Please understand that my intent is to re-familiarize myself with the tests for this role. 

I have some stuff I'm working on that _may_ result in a large PR against this role, and I want to make sure that I update the tests accordingly.

That being said, is http://kitchen.ci/ the best place to go for docs?

**Comment by gingerwizard** [comment]
@strootman we may be looking for community members to assist with testing. This may include limited access to the test infrastructure. Reach out to me outside of this ticket.

Regards the above i believe i have resolved the xpack issues.  The other error needs investigating. Lets test this again.

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
LGTM. Merging.

**Pull request merged**
