### PR TITLE
Bugfixes XPack activation and ansible debugging

### PR DESCRIPTION
**Pull request by kremers**
.

### CODE REVIEW

**Comment by kremers** [comment]
Signed the CLA!

**Comment by jpcarey** [comment]
LGTM

**Comment by gingerwizard** [comment]
@kremers did you sign this under a different email address? I'd like to get this merged as its causing the x-pack tests to fail.

**Comment by gingerwizard** [comment]
@kremers if you can't sign the CLA with the same email address i will make a separate PR for this change. I consider it a fix that can't be reproduced uniquely.

**Comment by gingerwizard** [comment]
Closing in favour of https://github.com/elastic/ansible-elasticsearch/pull/361

Thanks @kremers for highlighting

**Pull request closed without merging**
