### PR TITLE
Added flag install_java (default true), to allow skipping java instal…

### PR DESCRIPTION
**Pull request by geoffroya**
…lation, in case it has already been done, without package manager.

Solves https://github.com/elastic/ansible-elasticsearch/issues/94

The flag can be used as follows:

```YAML
- name: Elasticsearch skipping Java install
  hosts: localhost
  roles:
    #expand to all available parameters
    - { role: elasticsearch, 
        install_java: false,
        es_instance_name: "node1", 
        es_data_dirs: "/opt/elasticsearch/data", 
        es_log_dir: "/opt/elasticsearch/logs", 
        es_work_dir: "/opt/elasticsearch/temp", 
        es_config: {
          node.name: "node1", 
          cluster.name: "custom-cluster",
          discovery.zen.ping.unicast.hosts: "localhost:9301",
          http.port: 9201,
          transport.tcp.port: 9301,
          node.data: false,
          node.master: true,
          bootstrap.mlockall: true,
          discovery.zen.ping.multicast.enabled: false } 
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 1g
```

### CODE REVIEW

**Comment by karmi** [comment]
@geoffroya, thanks for the patch, the CLA doesn't seem to pass though, maybe it's because you have used a different e-mail in your commit than when signing CLA. Can you add both of those to your Github profile and comment here? That should trigger a new check.

**Comment by geoffroya** [comment]
@kami I used the email linked to my github account. I changed my profile so it is not hidden.

**Comment by geoffroya** [comment]
CLA doesn't seem to be happy :disappointed: 
Anything can be done for it?

**Comment by jakommo** [comment]
@karmi could you please check again?

**Comment by karmi** [comment]
Hi @geoffroya, you've used your Gmail address when signing the CLA, but your company e-mail when committing in Git (see the patch[](https://patch-diff.githubusercontent.com/raw/elastic/ansible-elasticsearch/pull/101.patch)). That's completely fine, as long as you add both of them to your Github profile -- they can be hidden, it's just a way for Github to link your username to emails, which our systems rely on.

I've re-verfied the PR just now, and it's still red, are you sure you added _both_ of those e-mails?

Alternatively, use `git commit --author` option to commit with a different e-mail and force push the PR.

**Comment by gingerwizard** [comment]
@geoffroya can you try adding your company email to your github or use the git commit --author option as karmi suggests

**Comment by sirkjohannsen** [comment]
+1

**Comment by gingerwizard** [comment]
Closing in favour of https://github.com/elastic/ansible-elasticsearch/pull/107

**Pull request closed without merging**
