### PR TITLE
Fix 2 idempotence issues

### PR DESCRIPTION
**Pull request by ddidier**

### CODE REVIEW

**Comment by ddidier** [comment]
Any news?

**Comment by ddidier** [comment]
I just signed the CLA, is there anything else I must do?

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by rusnyder** [comment]
I feel like it would be a good idea to add idempotence testing w/ this PR, particularly since it's as simple as adding a flag to the kitchen configuration:

```yaml
---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  ...
  idempotency_test: true
```

**Comment by gingerwizard** [comment]
We seem to have test issues which aren't associated with this specific PR.  I'll focus on resolving these and then revisit this shortly.

**Comment by gingerwizard** [comment]
Retesting now tests are fixed. @rusnyder i agree re idempotent test. I believe we have a ticket. I'll local at ironing out any issues.
Jenkins, test it!

**Comment by gingerwizard** [comment]
Jenkins, test it!

**Comment by gingerwizard** [comment]
The failures here are not related to the changes. I'm satsified these are good and will merge. I'll backport these to master also.

**Pull request merged**
