### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by gredinger**
Tiny change is tiny

### CODE REVIEW

**Comment by gredinger** [comment]
I've signed the CLA if someone can re-run the check. Kinda silly for a letter.

**Comment by jakommo** [comment]
@gredinger CLA checker is still red. Did you sign with the same email that you used for the commit?

**Comment by gredinger** [comment]
One last check? I've re-signed the agreement using my email.

**Comment by Crazybus** [comment]
@gredinger Thanks for this! It may only be a single letter but I'm sure it will have a huge affect ;)

**Pull request merged**
