### PR TITLE
Refactor deprecated version_compare filter calls

### PR DESCRIPTION
**Pull request by SlothOfAnarchy**
Previously, each of the calls generated a warning: "Using tests as filters is deprecated. Instead of using `result|version_compare` use `result is version_compare`. This feature will be removed in version 2.9.".

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @SlothOfAnarchy, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/ansible-elasticsearch/pull/523.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
Thanks for adding this in!

**Pull request merged**
