### PR TITLE
Disable the Netty recycler

### PR DESCRIPTION
**Pull request by cinience**
https://github.com/elastic/elasticsearch/pull/22452

### CODE REVIEW

**Comment by jpcarey** [comment]
The linked PR also has
`+-Dio.netty.allocator.type=unpooled`
Which seems missing in this.

**Comment by jasontedor** [comment]
@jpcarey That change was reverted in elastic/elasticsearch@f1ee2243b7e68eb697da1e8b70acdae89add5203.

**Comment by jakommo** [comment]
@cinience mind signing the CLA so I can merge this?

**Comment by cinience** [comment]
@jakommo  done

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by jakommo** [comment]
Thanks @cinience

**Comment by jakommo** [comment]
The failed thest seem not related to this, so I'm merging. 
Thanks for contributing @cinience

**Pull request merged**
