### PR TITLE
 Template log4j.properties for ES v7 

### PR DESCRIPTION
**Pull request by fabiogermann**
Introduce changes for the logging property file to be compatible with ES v7

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @fabiogermann, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/ansible-elasticsearch/pull/598.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @fabiogermann,
Thank you for your PR ❤️ 

While updating log4j template for Elasticsearch 7.X is really useful, I wonder if we still need to maintain a specific log4j template into this Ansible role.

After a quick review of the template I don't see any dynamic values inside except conditionals related to Elasticsearch version.

Maybe we should instead keep the `log4j2.properties` file already provided by Elasticsearch packages which is always up to date. WDYT?

**Comment by jmlrt** [comment]
related to https://github.com/elastic/ansible-elasticsearch/issues/577

**Comment by jmlrt** [comment]
I'm closing this PR as we handled it with #637

**Pull request closed without merging**
