### PR TITLE
Define a proxy for plugin installation

### PR DESCRIPTION
**Pull request by barryib**
Address the issue [ansible-elasticsearch #4](https://github.com/elastic/ansible-elasticsearch/issues/4) which add proxy for plugin installation and more generally es_proxy_host and es_proxy_port for global usage. 

Right now, it’s only used for plugins installation. In the futur, it can be used (or defined) in the java_opts within the default file for instance (elasticsearch.j2)

### CODE REVIEW

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
Thank you so much for the contribution! I'll let jenkins do its magic.
In the meantime could you sign the CLA?
Thanks!

**Comment by barryib** [comment]
@electrical I signed the CLA, but I don't know if it applied on this PR

**Comment by barryib** [comment]
Never mind. I was in the hurry :)

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
failed some runs so trying again.

**Comment by barryib** [comment]
@electrical I think there are version incompatibility between net-ssh and ruby during tests. In all failed tests, I got this error: `Gem::InstallError: net-ssh requires Ruby version >= 2.0.`

**Comment by electrical** [comment]
Yeah. will do some tests locally and fix the Gemfile.

**Comment by gingerwizard** [comment]
Hi @barryib picking this up as @electrical isn't focused on this anymore.  Lets get it tested again and ill see if i can resolve.

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
@barryib If the tests pass ill merge

**Comment by gingerwizard** [comment]
jenkins, test it

**Comment by gingerwizard** [comment]
LGTM

**Pull request merged**
