### PR TITLE
Include RedHat 7 in distributions that should use systemd (fixes #249)

### LINKED ISSUE #249: Can't restart service on RHEL
Ansible 2.2.1.0 on RHEL 7.3

```
- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
```
Leads to:

```
   elasticsearch: RUNNING HANDLER [roles/elasticsearch : restart elasticsearch] ******************
   elasticsearch: fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Service is in unknown state", "status": {}}
   elasticsearch: to retry, use: --limit @/tmp/packer-provisioner-ansible-local/main.retry
   elasticsearch:
   elasticsearch: PLAY RECAP *********************************************************************
   elasticsearch: 127.0.0.1                  : ok=39   changed=19   unreachable=0    failed=1
```
Then I ran this command on the server
```
$ systemctl status elasticsearch
elasticsearch.service - LSB: This service manages the elasticsearch daemon
   Loaded: loaded (/etc/rc.d/init.d/elasticsearch; bad; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

$echo $?
3
```

Looks like its an issue with this status response.

### PR DESCRIPTION
**Pull request by dmcd**

### CODE REVIEW

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by gingerwizard** [comment]
Jenkins, test it!

**Comment by gingerwizard** [comment]
Jenkins, test it!

**Comment by gingerwizard** [comment]
Ok single test failure but i don't think its related to the PR. Try again then ill investigate.

Jenkins, test it!

**Comment by gingerwizard** [comment]
LGTM. Thanks @elasticmachine

**Comment by aeonicgray** [comment]
Could you merge this into the 2.x code line as well?

**Pull request merged**
