### PR TITLE
Xpack

### PR DESCRIPTION
**Pull request by nullkarma**

### CODE REVIEW

**Comment by gingerwizard** [comment]
Whilst i like this, i think we need a test. I will be adding some tests for x-pack, where we don't enable security. I'll merge this PR into this PR. @nullkarma please sign the CLA.

**Comment by nullkarma** [comment]
signed. Thanks @gingerwizard

**Comment by gingerwizard** [comment]
this looks good to me. The only challenge i have with this is how to test it. Sugegstions welcome.

**Comment by gingerwizard** [comment]
I think we can test this just by doing an x-pack install and using an the official x-pack url as the custom url @nullkarma 

I'm adding another test to reproduce an issue tomorrow. I'll merge as part of that.

**Comment by gingerwizard** [comment]
@nullkarma im going to merge this locally, add a test and make a seperate PR. Is stated above i think this is good, it just needs a test.

**Comment by gingerwizard** [comment]
Merged under https://github.com/elastic/ansible-elasticsearch/pull/365

Thanks again @nullkarma

**Pull request merged**
