### PR TITLE
Add secure storage for email password

### PR DESCRIPTION
**Pull request by rs-garrick**
Store a provided email password in the keystore.

### CODE REVIEW

**Comment by rs-garrick** [comment]
It's been over 2 weeks and noone has looked at this.  Am I supposed to do something to catch someone's attention?

**Comment by jmlrt** [comment]
Hi @rs-garrick,
Thanks for submitting this PR. Sorry for the delays, we don't currently have time for review but we'll circle back once we can review it.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by tung-huynh** [comment]
Can we take a look on this please?

**Comment by rs-garrick** [comment]
This is well past 30 days.  I guess mark it stale and forget about it forever.

**Comment by jmlrt** [comment]
@rs-garrick,
As already mentionned we currently don't have time for this review.
Some Issues/PR can wait 3 months before we're able to do a proper review.
I know that's not ideal for contributors like you and I'm sorry about that, but we do our best to handle community issues and contributions to the many repositories we manage and our internal work at Elastic.

**Comment by rs-garrick** [comment]
I don't feel like being responsible for this forever. If someone else wants it, that's fine with me.

**Pull request closed without merging**
