### PR TITLE
fix version and add missing whitespace

### PR DESCRIPTION
**Pull request by davidak**

### CODE REVIEW

**Comment by davidak** [comment]
I just signed the CLA but you have to wait for the CLA of my employer what could take a bit longer.

Then you are allowed to use my whitespace.

**Comment by jakommo** [comment]
Thanks @davidak .
The CLA checker had a green check, so it looks like your signature was good.

>  but you have to wait for the CLA of my employer what could take a bit longer.

What do you mean by that?

**Comment by davidak** [comment]
@jakommo i signed "An individual contributing under an existing company contributor agreement" CLA, but there is no "existing company contributor agreement" yet.

**Comment by jakommo** [comment]
Ok, I see. Did you select the wrong thing or why did you go for "under an **existing** company contributor agreement" if it does not exist yet?

**Comment by davidak** [comment]
@jakommo my employer wanted to do that but havn't yet. Was that not checked by your system?

**Comment by jakommo** [comment]
As far as I know we trust you to select the appropriate setting.
When you sign saying that there is an existing agreement you basically confirm that with your signature.
At least that's my understanding. 

Anyways, I reverted the merge and reached out to one of my colleagues to clarify.

**Comment by davidak** [comment]
@jakommo Thanks and sorry for the trouble.

**Pull request merged**
