### PR TITLE
Typo in Makefile

### PR DESCRIPTION
**Pull request by victorgs**
s/cerify/verify/g

### CODE REVIEW

**Comment by Crazybus** [comment]
This is a duplicate of https://github.com/elastic/ansible-elasticsearch/pull/537. I'm going to keep this one open for now though since I'm waiting on the contributor to sign the CLA.

**Comment by victorgs** [comment]
Sorry for the duplicate , i didn't check the PR's opened 👀

**Comment by pemontto** [comment]
This one has the CLA signed, can this be approved over #537?

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
