### PR TITLE
initial 6.x support

### PR DESCRIPTION
**Pull request by remil1000**
here's an attempt to implement 6.0.0 support

tested with 5.6.4 for backward compatibility and with 6.0.0

### Using following playbook.yml
```
- hosts: elastic1
  become: true
  roles:
    - role: ansible-elasticsearch
      es_instance_name: "default_node"
      es_data_dirs: "/data/elasticsearch/data"
      es_config:
        cluster.name: "test-cluster"
        discovery.zen.ping.unicast.hosts: "{{ groups[es_masters_group] | map('regex_replace', '$', ':9300') | list }}"
        discovery.zen.minimum_master_nodes: 2
        http.port: 9200
        transport.tcp.port: 9300
        node.data: "{{ es_data_node | bool }}"
        node.master: "{{ es_master_node | bool }}"
        bootstrap.memory_lock: false
        # we need to listen on routable interfaces
        # but no vagrant management interface as it is not routable
        # and listening on local interfaces (loopback) is useful for mon/kibana
        network.host: "{{ ansible_all_ipv4_addresses | difference(['10.0.2.15']) | union(['_local_']) }}"
  vars:
    es_major_version: 6.x
    es_version_lock: false
    es_api_port: 9200
    es_version: 6.0.0
```

### and inventory
```
[elastic1:children]
elastic1_masters
elastic1_datas

[elastic1:vars]
es_masters_group=elastic1_masters

[elastic1_masters]
master[1:2].vagrant.test es_data_node=no es_master_node=yes

[elastic1_datas]
data[1:2].vagrant.test es_data_node=yes es_master_node=no
```

hope this will help

### CODE REVIEW

**Comment by remil1000** [comment]
CLA signing is in progress, will come back at you when it's done

**Comment by gbolo** [comment]
well done

**Comment by abraxxa** [comment]
Can we please get a time frame when this will be merged? Thanks!

**Comment by kakoni** [comment]
1) templates/elasticsearch.j2 needs some addons, it needs to have
`ES_PATH_CONF={{conf_dir}}`

2) init/redhat/elasticsearch.j2 daemon has `-Edefault.path.logs` .. opts, need to be removed for 6.x

**Comment by shribigb** [comment]
I am testing your pull request with x-pack enabled. It fails to install x-pack. It requires ES_PATH_CONF to be set in environment. 
Additional changes:
tasks/xpack/elasticsearch-xpack-install.yml
Add following for all the tasks where environment is set.  
    ES_PATH_CONF: "{{ conf_dir }}"

**Comment by kjkurtz** [comment]
ES_PATH_CONF also needs to be added to elasticsearch-plugins.yml where environment is used. I'm doing an upgrade from 5.6.x to 6.1.x and when I tell it to reinstall plugins, it fails to run the task 'Remove elasticsearch plugins' without it.

**Comment by rahulwa** [comment]
As @kjakman mentioned, we need to export `ES_PATH_CONF={{ conf_dir }}` while installing and removing plugins.

**Comment by cyrilleverrier** [comment]
Add this patch: https://github.com/remil1000/ansible-elasticsearch/pull/1

**Comment by jmataa** [comment]
FYI: Additional ES_PATH_CONF updates are here for 6.1.x as stated by kjkurtz:

https://github.com/andyshinn/ansible-elasticsearch/tree/6.x
https://github.com/andyshinn/ansible-elasticsearch/pull/1

**Comment by Crazybus** [comment]
Hi @remil1000!

 For the last few months this playbook hasn't had an active maintainer. I'm now stepping up to take ownership of this playbook with the immediate goal of getting 6.x support tested and working. 

Unfortunately there were already three open pull requests with varying levels of 6.x support. This meant I had the hard job of picking the pull request which appeared to be the most complete and start fixing up the tests to run on 5.x and 6.x. This PR ended up being https://github.com/elastic/ansible-elasticsearch/pull/408 because it also contained documentation updates. I have just opened PR: https://github.com/elastic/ansible-elasticsearch/pull/412 where I am fixing up all the tests to make sure they are passing for 5.x and 6.x across all platforms. 

I have also added some pull request [automated testing](https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+pull-request/) to make it easier to contribute in the future. 

So thank you so much for your contribution and I hope to see more contributions again from you in the future.

Cheers,

Michael

**Comment by abraxxa** [comment]
Thanks @Crazybus!

**Pull request closed without merging**
