### PR TITLE
Restart on config change

### LINKED ISSUE #168: Service not restarted on config change
The elasticsearch service does not seem to be restarted when es_config is changed even with `es_restart_on_change` set as true.

Adding this config `es_config: { action.auto_create_index: false }`

### PR DESCRIPTION
**Pull request by rcwsr**
Fixes #168

### CODE REVIEW

**Comment by rcwsr** [comment]
We have submitted our CLA

**Comment by jakommo** [comment]
@karmi could you please check, why its failing ?

**Comment by jakommo** [comment]
Thanks @rcwsr. Did you use the same email address for the commit and the CLA?

**Comment by karmi** [comment]
@rcwsr, I don't see any CLA signature with your name and/or e-mail in our records, can you contact me via e-mail, if you are sure you did sign and have received the copy?

**Comment by rcwsr** [comment]
Ah the commit may have been under my personal email, not the organisation's.

**Comment by rcwsr** [comment]
I can create a new PR with that email, if that would solve it?

**Comment by karmi** [comment]
@rcwsr, the details about the commit are [here](https://patch-diff.githubusercontent.com/raw/elastic/ansible-elasticsearch/pull/169.patch), but I haven't been successful when trying to find you in our records by your surname... Can you send me the name of the organization and the e-mail used for the signature, either here or by e-mail?

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by jakommo** [comment]
@karmi CLA checker indicates all good now, is this correct?

**Comment by karmi** [comment]
@jakommo: Yes, it is -- we have resolved it with Robin over e-mail.

**Comment by jakommo** [comment]
Jenkins, test it!

**Comment by jakommo** [comment]
Merged, thanks for contributing @rcwsr

**Pull request merged**
