### PR TITLE
Update users_roles.j2

### PR DESCRIPTION
**Pull request by jurim76**
Fix typo

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @jurim76,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement

**Comment by jurim76** [comment]
> Hi @jurim76,
> Thanks for your PR.
> Can you sign the CLA: https://www.elastic.co/contributor-agreement

Ok, it's done.

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
