### PR TITLE
install openjdk-8 and ca-certificates from backports

### PR DESCRIPTION
**Pull request by mgodlewski**
This should fix issue #316

### CODE REVIEW

**Comment by gingerwizard** [comment]
I don't feel qualified to comment on this. @dliappis maybe?

**Comment by gingerwizard** [comment]
@jpcarey maybe you have some thoughts here?

**Comment by jpcarey** [comment]
@mgodlewski do you have any further supporting information. Both debian8 and 9 seem to have the necessary components to install `openjdk-8-jre-headless` without need for using backports.

@gingerwizard I'd favor removing java installation from this role. If a user wants to use backports (, that should be an external dependency of installing / provisioning elasticsearch.

https://backports.debian.org/Instructions/
> Backports are recompiled packages from testing (mostly) and unstable (in a few cases only, e.g. security updates) in a stable environment so that they will run without new libraries (whenever it is possible) on a Debian stable distribution
> 
> Backports cannot be tested as extensively as Debian stable, and backports are provided on an as-is basis, with risk of incompatibilities with other components in Debian stable. Use with care!

**Comment by gingerwizard** [comment]
@jpcarey the plans is indeed to remove. I propose we close the PR and begin work on removing Java as a priority.

**Pull request closed without merging**
