### PR TITLE
allow max threads to be configured

### PR DESCRIPTION
**Pull request by ryanpineo**

### CODE REVIEW

**Comment by gingerwizard** [comment]
LGTM. Needs CLA @ryanpineo

**Comment by ryanpineo** [comment]
signed it now

**Comment by gingerwizard** [comment]
@ryanpineo did you use a different email address than that which you made the PR?

**Comment by ryanpineo** [comment]
Looks like I made this PR using my work email and I signed the CLA with my personal one.  I've now signed it with both.

**Comment by gingerwizard** [comment]
That doesn't seem to have resolved the issue. I'll investigate

**Comment by gingerwizard** [comment]
@karmi are you able to see why the CLA isn't being accepted here?

**Comment by ryanpineo** [comment]
I did a force push which seems to have triggered the CLA check again @gingerwizard

**Comment by gingerwizard** [comment]
@ryanpineo excellent merging. I'll add a test. Thanks!

**Pull request merged**
