### PR TITLE
Allow user to specify the http schema.

### PR DESCRIPTION
**Pull request by xocasdashdash**
This is a really simple fix that would allow us to use this module with a https elastic search. There is a PR #620 that would also allow for this to be done but this is a much smaller fix that can hopefully be merged faster. 

To avoid issues with that PR once this one is merged (or discarded) I've used the same variables as those defined by #620

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @xocasdashdash, thanks for your work on this PR.
Also I like incremental improvements when possible, #620 has already been approved and will be merged this week so I'm not sure we'll need this one in addition.

**Comment by xocasdashdash** [comment]
@jmlrt That's fantastic! Once it's merged, will a release be done soon? Right now I'm using my fork but once the PR is merged I can go back to using this

**Comment by jmlrt** [comment]
>Once it's merged, will a release be done soon
Yep next release including TLS should be really soon :)

**Comment by xocasdashdash** [comment]
Cool thanks!

**Pull request closed without merging**
